IMPORTING LIBRARIES



In [ ]:
import numpy as np
import pandas as pd
from tensorflow.keras import datasets


IMPORTING THE DATASETS


In [ ]:
(x_train,y_train),(x_test,y_test)=datasets.mnist.load_data()

In [ ]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [ ]:
y_train.shape

(60000,)

In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
x_test.shape

(10000, 28, 28)

In [ ]:
y_test.shape

(10000,)

In [ ]:
#the neural network only accepts the 3*3 matrix so converting the data into the (28,28,1) form
width,height=28,28
input_shape=(width,height,1)
input_shape


(28, 28, 1)

In [ ]:
x_train=x_train.reshape(x_train.shape[0],28,28,1)
x_test=x_test.reshape(x_test.shape[0],28,28,1)

In [ ]:
x_test
x_train

array([[[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],


In [ ]:
x_train.shape

(60000, 28, 28, 1)

In [ ]:
y_train.shape

(60000,)

In [ ]:
#for evulation purpose importing the another evulate data
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.1)

In [ ]:
len(x_train)

54000

In [ ]:
len(x_val)

6000

In [ ]:
y_val.shape

(6000,)

In [ ]:
#normalizing the data,by feature scaling the data by standadising
x_train=(x_train-x_train.mean())/x_train.std()
x_val=(x_val-x_train.mean())/x_val.std()
x_test=(x_test-x_test.mean())/x_test.std()

In [ ]:
x_train

array([[[[-0.42408199],
         [-0.42408199],
         [-0.42408199],
         ...,
         [-0.42408199],
         [-0.42408199],
         [-0.42408199]],

        [[-0.42408199],
         [-0.42408199],
         [-0.42408199],
         ...,
         [-0.42408199],
         [-0.42408199],
         [-0.42408199]],

        [[-0.42408199],
         [-0.42408199],
         [-0.42408199],
         ...,
         [-0.42408199],
         [-0.42408199],
         [-0.42408199]],

        ...,

        [[-0.42408199],
         [-0.42408199],
         [-0.42408199],
         ...,
         [-0.42408199],
         [-0.42408199],
         [-0.42408199]],

        [[-0.42408199],
         [-0.42408199],
         [-0.42408199],
         ...,
         [-0.42408199],
         [-0.42408199],
         [-0.42408199]],

        [[-0.42408199],
         [-0.42408199],
         [-0.42408199],
         ...,
         [-0.42408199],
         [-0.42408199],
         [-0.42408199]]],


       [[[-0.42408199],


In [ ]:
#encoding the catgorical values of y_test and y_val
y_train

array([1, 3, 9, ..., 5, 9, 6], dtype=uint8)

In [ ]:
num_labels=10
from tensorflow import keras


In [ ]:
y_train=keras.utils.to_categorical(y_train)

In [ ]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

MODEL

In [ ]:
#bulding a model lenet5 model a 5 layered model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,AveragePooling2D,Dropout,Flatten,Input,Conv2D,MaxPooling2D

In [ ]:
model=Sequential()
model.add(Conv2D(6,kernel_size=(5,5),strides=(1,1),activation='tanh',input_shape=(28,28,1)))
model.add(AveragePooling2D(pool_size=(2,2),strides=(1,1)))
model.add(Conv2D(16,kernel_size=(5,5),strides=(1,1),activation='tanh'))
model.add(AveragePooling2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(120,kernel_size=(5,5),strides=(1,1),activation='tanh'))
model.add(Flatten())
model.add(Dense(84,activation='tanh'))
model.add(Dense(num_labels,activation='Softmax'))

In [ ]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_15 (Conv2D)          (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d_10 (Aver  (None, 23, 23, 6)         0         
 agePooling2D)                                                   
                                                                 
 conv2d_16 (Conv2D)          (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_11 (Aver  (None, 9, 9, 16)          0         
 agePooling2D)                                                   
                                                                 
 conv2d_17 (Conv2D)          (None, 5, 5, 120)         48120     
                                                                 
 flatten_5 (Flatten)         (None, 3000)             

In [ ]:
#compiling the model
model.compile(loss=keras.losses.categorical_crossentropy,optimizer='adam',metrics=['accuracy'])



In [ ]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
y_val=keras.utils.to_categorical(y_val)

In [ ]:
y_val

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
history=model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=1,validation_data=(x_val,y_val))

Epoch 1/5
1688/1688 [==============================] - 67s 39ms/step - loss: 0.0613 - accuracy: 0.9811 - val_loss: 0.5118 - val_accuracy: 0.8298
Epoch 2/5
1688/1688 [==============================] - 69s 41ms/step - loss: 0.0580 - accuracy: 0.9821 - val_loss: 0.3289 - val_accuracy: 0.8927
Epoch 3/5
1688/1688 [==============================] - 71s 42ms/step - loss: 0.0537 - accuracy: 0.9833 - val_loss: 0.3574 - val_accuracy: 0.8835
Epoch 4/5
1688/1688 [==============================] - 62s 37ms/step - loss: 0.0537 - accuracy: 0.9836 - val_loss: 0.6785 - val_accuracy: 0.8115
Epoch 5/5
1688/1688 [==============================] - 65s 38ms/step - loss: 0.0509 - accuracy: 0.9844 - val_loss: 0.3662 - val_accuracy: 0.8772


In [ ]:
y_test=keras.utils.to_categorical(y_test)

In [ ]:
score=model.evaluate(x_test,y_test,verbose=1)

313/313 [==============================] - 4s 11ms/step - loss: 0.0529 - accuracy: 0.9843


In [ ]:
score

[0.052874669432640076, 0.9843000173568726]

accuracy of 98.4 percent